# Generated by Django 5.1.4 on 2025-01-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_alter_blog_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_tag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
